### PR TITLE
vers port

### PR DESCRIPTION
**Pull request by faassen**
Here's the PR of the vers port. Please note the following:

* I've modified the README to report on the port, etc, which clearly needs modification if this is to be a new release of fm-index directly. I'll prepare this should you accept this PR.

* there are a lot of typecasts from u64 and usize and back. This is because Vers currently uses usize in its API. I spoke to the author of Vers, @Cydhra, who [said](https://github.com/Cydhra/vers/issues/17#issuecomment-2553699969) that in version 2.0 Vers is going to be changed to use u64 in more places, so I've left the nasty typecasts in. It may lead to problems on 32 bit machines.

Let me know what you think!

### CODE REVIEW

**Review by ajalab — APPROVED** [review]
I checked all the commits, and they look good to me! Also I really appreciate all the corrections you have made for this code including clippy and grammar fix.

I believe this PR will be ready for merge after we update the crate name (`fm-index-vers` to `fm-index`) in documents for this repository.

**Comment by faassen** [comment]
Thank you! I really appreciate all the hard work you did for this crate, including literature references. I will adjust documentation and let you know!

**Comment by faassen** [comment]
I've just updated the PR so modify the documentation so it fits `fm-index` again.

A note about releasing and  `CHANGES.md`. I've added the note from the README into it. I expect you'll want to make a 0.2.0 release. If you look at CHANGES.md you see it starts;

```
<!-- next-header -->

## [Unreleased] - ReleaseDate
```

This is because I use the 'cargo release' tool to do releasing. It automatically updates version numbers and updates the CHANGES.md too with the release date. (it doesn't try to turn commit messages into a changelog; I prefer handwritten changelogs)

https://github.com/crate-ci/cargo-release

Once you have it installed, you can try a release by using

`cargo release minor` (which should update to 0.2.0 as that's a minor version update)

and once you're happy you can do:

`cargo release minor --execute` to get everything uploaded.

If you want to see an example of a changelog maintained this way:

https://github.com/faassen/xot/blob/main/CHANGES.md

But if you want to maintain the changelog in another way that's fine with me  too - I haven't figured out how to use the github "releases" feature properly with this yet, for instance. I just figured we need a place to inform people about changes like this.

**Comment by ajalab** [comment]
@faassen I successfully released fm-index [0.2.0](https://crates.io/crates/fm-index/0.2.0). Again, thank you for your kind help!

**Comment by faassen** [comment]
Thank you so much! I will go and deprecate my fork so people don't get confused.

**Pull request merged**
